apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: kys
  namespace: kys
spec:
  replicas: 1
  serviceName: kys-server
  selector:
    matchLabels:
      app: kys
  template:
    metadata:
      labels:
        app: kys
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /opt/mssql/bin/sqlservr
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: M@dStr@ming2018
        - name: DEBIAN_FRONTEND
          value: noninteractive
        image: microsoft/mssql-server-linux
        imagePullPolicy: Always
        name: kys
        ports:
        - containerPort: 1433
          name: sql
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: 1m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: kys-vol
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: kys-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 400Gi
        storageClassName: default
---
apiVersion: v1
kind: Service
metadata:
  name: kys-server
spec:
  clusterIP: None
  ports:
  - name: sql
    port: 1433
    targetPort: 1433
  selector:
    app: kys		