# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2018-08-09T20:16:18Z
  generation: 31
  labels:
    account-id: 45872a4e-39b4-41da-ad6d-6f3ee165de68
    application-id: 717aa7e0-37a7-4112-bf2c-e8d5ed7b9c4f
    service-id: a41239bf-40d1-4980-8cea-ad0ea9ca7571
  name: a41239bf-40d1-4980-8cea-ad0ea9ca7571
  namespace: 717aa7e0-37a7-4112-bf2c-e8d5ed7b9c4f
  resourceVersion: "22852466"
  selfLink: /api/v1/namespaces/717aa7e0-37a7-4112-bf2c-e8d5ed7b9c4f/replicationcontrollers/a41239bf-40d1-4980-8cea-ad0ea9ca7571
  uid: 12e47a41-9c11-11e8-a15b-06a80570618e
spec:
  replicas: 1
  selector:
    service-id: a41239bf-40d1-4980-8cea-ad0ea9ca7571
  template:
    metadata:
      creationTimestamp: null
      labels:
        account-id: 45872a4e-39b4-41da-ad6d-6f3ee165de68
        application-id: 717aa7e0-37a7-4112-bf2c-e8d5ed7b9c4f
        service-id: a41239bf-40d1-4980-8cea-ad0ea9ca7571
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/bash
        - -c
        - apt-get update; apt-get install -y tzdata; ln -fs /usr/share/zoneinfo/America/Toronto
          /etc/localtime; dpkg-reconfigure --frontend noninteractive tzdata; apt install
          -y realmd krb5-user software-properties-common python-software-properties
          packagekit samba sssd ntp winbind adcli freeipa-client libpam-winbind; cp
          /usr/share/doc/libpam-winbind/examples/pam_winbind/pam_winbind.conf /etc/security/pam_winbind.conf;
          rm /etc/ntp.conf; rm /etc/krb5.conf; rm /etc/samba/smb.conf; rm /usr/lib/realmd/realmd-defaults.conf;
          wget https://raw.githubusercontent.com/MagalixTechnologies/mgx-templates-configs/master/vic/etc/resolv.conf
          ; wget  https://raw.githubusercontent.com/MagalixTechnologies/mgx-templates-configs/master/vic/etc/ntp.conf;
          wget  https://raw.githubusercontent.com/MagalixTechnologies/mgx-templates-configs/master/vic/etc/krb5.conf;
          wget  https://raw.githubusercontent.com/MagalixTechnologies/mgx-templates-configs/master/vic/etc/samba/smb.conf;
          wget  https://raw.githubusercontent.com/MagalixTechnologies/mgx-templates-configs/master/vic/usr/lib/realmd/realmd-defaults.conf;
          cat resolv.conf > /etc/resolv.conf; echo '10.4.2.194 LESARAPP.VIC.LOCAL'
          >> /etc/hosts; mv ntp.conf /etc/ntp.conf; mv krb5.conf /etc/krb5.conf; mv
          smb.conf /etc/samba/smb.conf; mv realmd-defaults.conf /usr/lib/realmd/realmd-defaults.conf;
          mv sssd.conf /etc/sssd/sssd.conf; chmod 600 /etc/sssd/sssd.conf; service
          dbus start; service samba start; service ntp start; service smbd start;
          service samba-ad-dc start; service winbind start; echo Vic@MedStreaming123|
          realm join VIC.LOCAL -U 'medsupport@VIC.LOCAL' -v&& sssd -D&& mkdir -p /var/opt/mssql&&
          mkdir -p /var/opt/mssql/secrets&& printf "%b" "addent -password -p MSSQLSvc/vic.medstream.magalix.cloud:1433@VIC.LOCAL
          -k 2 -e aes256-cts-hmac-sha1-96\nCVfr45tgBN\naddent -password -p MSSQLSvc/vic.medstream.magalix.cloud:1433@VIC.LOCAL
          -k 2 -e rc4-hmac\nCVfr45tgBN\nwkt /var/opt/mssql/secrets/mssql.keytab" |
          ktutil&& chmod 400 /var/opt/mssql/secrets/mssql.keytab&& /opt/mssql/bin/mssql-conf
          set network.kerberoskeytabfile /var/opt/mssql/secrets/mssql.keytab&& /opt/mssql/bin/mssql-conf
          set sqlagent.enabled true&& /opt/mssql/bin/sqlservr
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: M@dStr@ming2018
        - name: DEBIAN_FRONTEND
          value: noninteractive
        image: microsoft/mssql-server-linux
        imagePullPolicy: Always
        name: d7afb5b8-3bea-4f3d-a4cd-551aa6864984
        ports:
        - containerPort: 1433
          name: sql
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: 1m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssqldb
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - $(RECORD_NAME)
        - $(POD_IP)
        command:
        - bash
        - /start/updatedns.sh
        env:
        - name: ROUTE53_DEFAULT_HOSTED_ZONE_NAME
          value: medstream.magalix.cloud.
        - name: RECORD_NAME
          value: vic
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: amrfarid/awscli-dns
        imagePullPolicy: Always
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: cd129c1b-23a7-4081-8c77-2298282566ae
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 31
  readyReplicas: 1
  replicas: 1
